SELECT * 
FROM EMPLOYEE 
WHERE SALARY = (SELECT MAX(SALARY) FROM EMPLOYEE);

SELECT * 
FROM DEPARTMENT 
WHERE ID = (SELECT DEPARTMENT_ID FROM EMPLOYEE WHERE SALARY = (SELECT MAX(SALARY) FROM EMPLOYEE));

WITH DEPARTMENT_SALARY AS 
	(SELECT DEPARTMENT_ID, SUM(SALARY) AS SALARY
	FROM EMPLOYEE 
	GROUP BY DEPARTMENT_ID)
SELECT DEPARTMENT_ID
FROM DEPARTMENT_SALARY
WHERE DEPARTMENT_SALARY.SALARY = (SELECT MAX(SALARY) FROM DEPARTMENT_SALARY);

SELECT * 
FROM EMPLOYEE 
WHERE NAME LIKE "Р*н";